
# fly.toml file generated for soal-csugm on 2025-09-22T14:00:00Z

app = "soal-csugm"
primary_region = "sin"

[build]
  builder = "heroku/builder:22"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
